### ISSUE TITLE
trim abstract

### ISSUE THREAD

**Issue by dret** [w3c/automotive#104]
it seems that the current abstract is more an introduction than an abstract. it might help the spec's visibility to have a shorter, one- or two-paragraph abstract.

**Comment by wonsuk73** [comment]
Thanks for comment! @dret, I agreed. One or two paragraph abstract is typical shape of W3C spec.

**Comment by dret** [comment]
as a side note: http://www.w3.org/TR/2016/WD-vehicle-information-api-20160119 has a similarly long abstract. not quite as long but maybe also worth trimming.

**Comment by dret** [comment]
On 2016-10-22 11:42, Wonsuk Lee wrote:

> Thanks for comment! @dret https://github.com/dret, I agreed. One or
> two paragraph abstract is typical shape of W3C spec.

i'd be more than happy to help with reviewing/tweaking those paragraphs. 
i first have to read through the whole thing, though. thanks for the 
quick feedback!

**Comment by wonsuk73** [comment]
@dret I had updated abstract part! Thanks for the comment!
