### ISSUE TITLE
discrepancy between title and short title

### ISSUE THREAD

**Issue by dret** [w3c/automotive#107]
currently the title is "Vehicle Signal Server Specification" and the short title is "vehicle-information-service" (signal server vs. information service). to me, service makes much more sense (no consumer is interested in the appliance providing a service), but whatever it is, it should be consistent.

**Comment by rstreif** [comment]
Per Working Group Meeting: rename title to "Vehicle Information Service Specification"

**Comment by dret** [comment]
looks good to me!

**Comment by rstreif** [comment]
In addition per Working Group Meeting: name the companion document specifying the API "Vehicle Information API Specification"

**Comment by drkevg** [comment]
Updated name of server spec to be 'Vehicle Information Service Specification' and for references to client spec to 'Vehicle Information API Specification
