### ISSUE TITLE
[data-spec] Spelling / Grammar

### ISSUE THREAD

**Issue by acrofts84** [w3c/automotive#11]
5.5, 5.7 information information – repeated word. Multiple times.
5.7.1 Extra commas where readOnly may have been (copy and paste error)
6.17.1 Missing a couple of close brackets. "(Unit: percentage, 0%: empty, 100%: full"
6.25.2 ‘Simultanious’ spelling error
7 ‘(e.g., engine)’ extra comma
7.3.1 Add percentage symbols
7.3 7.5 Apostrophe “maintenance state of a vehicle’s ______” a few occurrences
8.4 mirrorPan “%0” instead of “0%”

**Comment by djensen47** [comment]
- [ ] One of the editors, @acrofts84, to fix in a pull request
