### ISSUE TITLE
Implementation Report Plan

### ISSUE THREAD

**Issue by Hirabayashi-KDDI** [w3c/automotive#123]
I have placed a draft (pptx version 01) of Implementation Report Plan (IRP)[1]　as a new issue  on the GitHub.　In a few days, web style document will be available.
[1] https://lists.w3.org/Archives/Member/member-automotive/2017Jan/att-0052/VISS_VIAS_Implementation_Report_Plan_-draft01.1.pptx
If any, please put comments on the issue.

**Comment by Hirabayashi-KDDI** [comment]
I generated VISS & VIAS Implementation Report Plan in web format, based on new drafts of VISS and VIAS .
[VISS&VIAS Implementation Report Plan.txt](https://github.com/w3c/automotive/files/988250/VISS.VIAS.Implementation.Report.Plan.txt)
[VISS&VIAS testing.zip](https://github.com/w3c/automotive/files/988258/VISS.VIAS.testing.zip)

**Comment by peterMelco** [comment]
I think this one can be closed . We will have a wiki page where we link to implementation reports. The content and format of the actual reports are not stated. It is, howeve,r good if the reports reflect upon the spec and pitfalls found during the implementation.
