### ISSUE TITLE
Make introduction non normative

### ISSUE THREAD

**Issue by drkevg** [w3c/automotive#127]
Comparing with old one, I feel that the introduction part of the current spec is a little too specific.
In my understanding, the introduction part is usually non-normative (So key words such as MAY/MUST/SHALL does not appear.)
Particularly, I would like to suggest that paragraphs refereeing websocket connection could be moved to the security section (initially raised by Junichi via email 11Jan17)

**Comment by rstreif** [comment]
I agree with @drkevg. The Introduction section contains too much detail on architecture and implementation. I feel that these details should actually go into the Architecture section. In addition, the Architecture section again has an Introduction subsection which should probably be renamed to something like "Overview". @drkevg do you want to take a stab at the improvements you suggest?

**Comment by paulboyes** [comment]
Giving credit where credit is due, this comment originated via email from Junichi Hashimoto.  Kevin graciously created the issue and hopes to resolve in the next couple of days.  "Thanks very much for the helpful feedback, I've raised issue #127 to capture this. Adam and I would hope to resolve in the next couple of working days."

**Comment by sou3ilow** [comment]
All, thank you for adressing this issue.

2017/01/12 午後1:45 "Paul J. Boyes" <notifications@github.com>:

**Comment by rstreif** [comment]
AR: Editors please verify if this request has been fulfilled. If not, please address accordingly.
