### ISSUE TITLE
Subscribe repsonse inconsistent

### ISSUE THREAD

**Issue by peterMelco** [w3c/automotive#141]
**Section: 8. Message Structure 
Cat: Subscribe**

When subscribing to signals the action attribute is not part of the return JSON message, this is inconsistent . The inconsistency makes testing ugly.

Suggestion: add "action", "subscribing" to respond message.

**Comment by acrofts84** [comment]
Hi Peter. Thanks for the comments. I agree that it is ugly. Urata-san mentioned this in #138, where I had assumed that the subscriptionNotification would return the action: "subscribe".

I agree that this is ugly and we should include something here. Maybe action = "subscription" or "subscriptionNotification"

**Comment by rstreif** [comment]
AR: Resolve the issue as suggested by this issue and issue #138: add action: "subscription" to the returned JSON.

**Comment by peterMelco** [comment]
Sounds good.

**Comment by acrofts84** [comment]
Action "subscription" added and merged
