### ISSUE TITLE
Undefined Wildcard behaviour for getVSS request 

### ISSUE THREAD

**Issue by peterMelco** [w3c/automotive#145]
Section: 8 Message Structure
Cat: getVSS

How is the wildcard defined ? Ex: Signal.Cabin.* returns subtree below Cabin ? If so what is the purpose of the * ?

**Comment by rstreif** [comment]
The getVSS request does not support wildcards.

If the requested path points to a leaf then the request will return the details of the leaf as shown by the example in the "VSS Request" section.

If the requested path points to a subtree then the request will return the entire subtree in structured nested form.

AR: Update the "VSS Request" section of the specification with a clarification and an example requesting a subtree.
