### ISSUE TITLE
[data-spec] YawRate exist. Roll and pitch are not necessary?

### ISSUE THREAD

**Issue by aShinjiroUrata** [w3c/automotive#16]
There is  "6.23 YawRate Interface" but no Pitch, Roll interfaces.
I guess, pitch and Roll are useful information for passenger comfotability.

**Comment by djensen47** [comment]
- [ ] @aShinjiroUrata to make a suggestion on how to update the spec to accommodate pitch and roll.

**Comment by aShinjiroUrata** [comment]
Made a pull request.
 https://github.com/w3c/automotive/pull/20

**Comment by aShinjiroUrata** [comment]
Already merged. I close this.
