### ISSUE TITLE
Use term "VISServer" instead of "WebSocket server"

### ISSUE THREAD

**Issue by rstreif** [w3c/automotive#164]
I suggest that in both specifications [VISS](http://w3c.github.io/automotive/vehicle_data/vehicle_information_service.html) and [VIAS](https://w3c.github.io/automotive/vehicle_information_api/vehicle_information_api_specification.html) we use the term `VISServer` instead of `WebSocket server`. This is more specific.

**Comment by wonsuk73** [comment]
@rstreif, the name of VISSever is fine to me. For making the spec kindly it would be good to add this term to terminology chapter of the spec.

**Comment by drkevg** [comment]
Agree that references to websocket server should change to 'VIS Server' for consistency with naming convention client spec..
