### ISSUE TITLE
[data-spec] Steering Wheel Left - Ambiguous

### ISSUE THREAD

**Issue by acrofts84** [w3c/automotive#17]
The steeringWheelLeft attribute name feels very ambiguous to me. Would this be better off as a Zone? Or a less ambiguous term e.g. leftHandDrive or driverSideLeft. Although I don't know how well these translate.

<pre>5.7.1 Attributes
steeringWheelLeft of type boolean, readonly , nullable
must return true if steering wheel is on left side of vehicle
</pre>

**Comment by djensen47** [comment]
- [ ] Ask previous editors for their comments on this.

**Comment by paulboyes** [comment]
- How to handle cars with no steering wheel?
- How to handle single seat car?
- Center steer wheel?
- Other interfaces?  Such as head unit location?  What similar interfaces are we missing?

**Comment by tripzero** [comment]
You could make it steeringWheelOrientation with just a zone attribute.
