### ISSUE TITLE
[data-spec, vehicle-spec] Remove etc from specification

### ISSUE THREAD

**Issue by peterMelco** [w3c/automotive#22]
From vehicle_spec.html : Abstract, 12
From data_spec.html : 6,6.26,6.27,12.1.2,12.1.3

A specification should not contain etc...either we need to define etc or we need to remove.

**Comment by paulboyes** [comment]
- [ ] Peter Winzell to go through the cases where "etc" is used and propose alternatives as appropriate.

**Comment by peterMelco** [comment]
target to deliver a review of etc by 26/6-15

**Comment by MelcoGot** [comment]
I have forked and made some changes.  I will now add a pull request for this and  If this is the wrong procedure please let me know of the correct way.  The review of this should be done of some one who is a native speaker of English. So, we avoid any limitations that the removal of etc brings.

**Comment by acrofts84** [comment]
Pull request <a href="https://github.com/w3c/automotive/pull/48">#48</a>

**Comment by wonsuk73** [comment]
Pull request #48 made conflict to be merged. So it has been done via Pull request #57 and #58
