### ISSUE TITLE
Remove "0105-getVss-no-path-success.html" test case?

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#222]
This test assertion is as below:
When the client makes a request with a correct 'getVSS' action without specifying 'path',
'VssSuccessResponse' is returned in which entire VSS tree is enclosed.

By the way the last f2f meeting at Birmingham, there was the consensus to make "path" attribute as a mandatory in vssRequest message. Therefore it might be removed from test cases.

@aShinjiroUrata Am I right?

**Comment by aShinjiroUrata** [comment]
Hi @wonsuk73 san

>  there was the consensus to make "path" attribute as a mandatory in vssRequest message.

Excuse me but I don't remember well about this particular point.
What was the reason to make `path` as mandatory?
However, it looks this consensus is already refrected on VISS spec, right?

If so, I will fix(or delete) the test assertion and the following test content. 
https://github.com/aShinjiroUrata/web-platform-tests/blob/dev-urata-vsss-test/vehicle/viss/0105-getVss-no-path-success.html

**Comment by wonsuk73** [comment]
@aShinjiroUrata As far as I understood there was the consensus to have "path" attribute as a mandatory even that is empty in Burmingham F2F. Because that is more easy to implement and less confusing when it is used. @acrofts84 Am I right? Do you have comment want to add? :-)

**Comment by acrofts84** [comment]
Hi All, 
Yes, we agreed to make the path mandatory for getVSS. As Wonsuk said, this is simpler. It also encourages the client to only request the data it requires - the VSS tree will be a significant data structure, so we should encourage the client to look at individual branches, rather than the entire tree where possible.

**Comment by aShinjiroUrata** [comment]
@wonsuk73 -san, @acrofts84 -san,

Thanks for explanation.
I understand that, 
- 'path' is mandatory 
- and/but empty path is acceptable.

I'll fix(or delete) the test assertion/test content.

**Comment by wonsuk73** [comment]
@aShinjiroUrata Thanks!
