### ISSUE TITLE
Missing normative reference to GENIVI Vehicle Signal Specification (VSS)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/automotive#229]
The spec relies on the GENIVI Vehicle Signal Specification (VSS) for its data model; it should thus be listed in the normative dependencies

**Comment by wonsuk73** [comment]
Hi. Dom(@dontcallmedom)!
Thanks for comment on this. I made PR for fixing that.

**Comment by aShinjiroUrata** [comment]
Thanks for pointing @dontcallmedom .
Thanks for PR @wonsuk73 .
PR has been merged in VIAS.

**Comment by acrofts84** [comment]
Thanks all, this has also been merged for VISS, so can close
