### ISSUE TITLE
Map VSS value spaces to EcmaScript types

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/automotive#234]
https://w3c.github.io/automotive/vehicle_information_api/vehicle_information_api_specification.html#dom-visvalue-value says the type of `value` depends on the details of the target in VSS - the exact mapping between the Franca IDL types and EcmaScript probably ought to be explicited.

**Comment by tguild** [comment]
VIAS is not presently continuing on REC track and was published as a Note.
