### ISSUE TITLE
getVSS test cases should be changed with getMetadata

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#240]
In VISS test suite below getVSS test cases should be changed with using getMetadata because VISS spec was updated like this.

0100-getVss-success.html
0105-getVss-no-path-success.html
0110-getVss-wildcard-success.html
0120-getVss-incorrect-error.html

**Comment by aShinjiroUrata** [comment]
Fixed by below commit/push.

https://github.com/aShinjiroUrata/web-platform-tests/commit/2361d584137579ffa8fe11e096ee0652aa4f082d

@wonsuk73 -san, could you try?

**Comment by aShinjiroUrata** [comment]
I close this since test runs well in my place.

With my prototype,  0100, 0105, 0120 succeeded and failed on 0110 because of lack of wildcard support.
All are expected result.
