### ISSUE TITLE
Error Info(number, reason, message) to subscribe request with filter for branch

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#242]
In current  [9. Server Side Filtering](https://w3c.github.io/automotive/vehicle_data/vehicle_information_service.html#server-side-filtering) part of VIS spec describe as below.

> Filters can only be applied for data which is represented by a primitive type, such as leaf nodes in the VSS tree, not entire branches. For example, a filter cannot be set on Signal.Drivetrain.InternalCombustionEngine.*, however it can be set on Signal.Drivetrain.InternalCombustionEngine.RPM.

By the way I couldn't find appropriate error number, reason and message in the [9.2 Errors](https://w3c.github.io/automotive/vehicle_data/vehicle_information_service.html#errors) part. If it is true it should be added.

**Comment by wonsuk73** [comment]
@acrofts84 @drkevg @aShinjiroUrata Does it make sence to you guys?

**Comment by acrofts84** [comment]
Hi Wonsuk. 

I think the logical response to this would be a 400 Bad Request, but I agree that the error message "The server is unable to fulfil the client request because the request is malformed." doesn't provide a satisfactory response. 

How about introducing 400 Bad Request "Filter requested on non-primitive type"?

**Comment by wonsuk73** [comment]
@acrofts84 That's good to me! But to be clear, error code is "400(Bad Request)" and message is "Filter requested on non-primitive type".So Error Reason need to be added. Right?

**Comment by acrofts84** [comment]
Good point. I think the reason has to be a bit more concise, so I think the best approach is:

Code: 400 (Bad Request) 
Reason: filter_invalid
Message: Filter requested on non-primitive type

**Comment by wonsuk73** [comment]
@acrofts84 Thanks!
