### ISSUE TITLE
[0320: multiple filter conditions]

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#243]
Goal of this test case is as below.
>If the client specifies two or more conditions among 'interval', 'range' and 'minimum change',
the client receives data when the specified multiple conditions are satisfied.

The test case send below subscribe request with filter as "{"interval":1000,"range":{"above":100,"below":20},"minChange":5}". But I am not sure this could be working because 1 Sec. interval mean server should give a notification to the subscriber in every 1 sec. But there is other mixed conditions with range and minChange for notification timing. 

@aShinjiroUrata what do you think?

>{"action":"subscribe","path":"Signal.Drivetrain.Transmission.Speed","requestId":"reqid-0320","filters":{"interval":1000,"range":{"above":100,"below":20},"minChange":5}}

**Comment by peterMelco** [comment]
propose to close due to inactivity.
