### ISSUE TITLE
testcase 0260-unsubscribeall-success.html does not success

### ISSUE THREAD

**Issue by aShinjiroUrata** [w3c/automotive#244]
With ETRI's VISServer implementation, testcase 0260 does not success.
Received code change request from @wonsuk73

**Comment by aShinjiroUrata** [comment]
Revised the test code by below commit.

https://github.com/aShinjiroUrata/web-platform-tests/commit/bff1997f0dae350fdb6793652bfab39dcf337905

**Comment by wonsuk73** [comment]
@aShinjiroUrata, Thanks! It's working well.

**Comment by aShinjiroUrata** [comment]
Thanks for feedback.
Then I close this.
