### ISSUE TITLE
Rework the WG's home page

### ISSUE THREAD

**Issue by tripu** [w3c/automotive#251]
To adopt at least the [WG's home page template](https://github.com/w3c/design/#contents). But even better if it's the new layout+design we're working on right now.

If the policy of the group is to use this repository only for specs (and not to keep the WG's pages), I'll move this issue under [`w3c/design`](https://github.com/w3c/design/issues) and work directly on `w3.org` space, instead of submitting a PR here.

**Comment by tripu** [comment]
@tanyeah is working on a redesign now :)

**Comment by tguild** [comment]
@tanyeah provided tremendous help on auto activity landing page and @tguild is following @plehegar and @tanyeah work on dynamic group page efforts
