### ISSUE TITLE
2018 draft charter changes

### ISSUE THREAD

**Issue by tguild** [w3c/automotive#256]
Collect feedback from Auto WG on the draft charter

**Comment by PatrickCQ** [comment]
Rephrasing of general scope: https://github.com/PatrickCQ/w3c-automotive/commit/4cf2ef5ad5c3a2f86fb176dc59eefb0707ec43eb

**Comment by PatrickCQ** [comment]
Emphasis on creating a pattern for an interface and not a protocol.
https://github.com/PatrickCQ/w3c-automotive/commit/a3b9d3ca5b80272430cb0957fa0fcdb06cfd3b54

**Comment by peterMelco** [comment]
Some comments:

1 Scope

 **Replace … with actual content or remove.**  
 
* Vehicle Data
    * vehicle brand, model, year, fuel type, transmission type, steering wheel position, tire pressure, oil level, wiper position, lights, doors, windows and seat settings as well as navigation, trip computer data, climate control data, speed, RPMs, acceleration, gears, …
* media
    * media control, track lists, …
* navigation
    * route manipulation, points of interests, …

2.1 Normative specifications

Should we define **“the vehicle universe”** or is that implicit ?

**Comment by tguild** [comment]
Charter long ago published and approved by W3M and AC
