### ISSUE TITLE
 Review on editing tools for writing RSI specs with W3C style

### ISSUE THREAD

**Issue by anawhj** [w3c/automotive#262]
To write a W3C specification, it needs to follow the guideline provided by W3C. You can see the guildeline including roles of W3C spec editors in the following link.
* How to edit W3C specs: https://www.w3.org/2003/Editors/
* Sample W3C specification: http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample

To build the spec document, we can consider a couple of major editing tools: Bikeshed, Respec
* Respec: https://github.com/w3c/respec/
* Bikeshed: https://github.com/tabatkins/bikeshed/

There would be pros and cons between Respec and Bikeshed. Someone mentioned that Respec would be easy to learn with zero installation, while Bikeshed would support several useful features such as cross-spec link, syntax error check so that it's suitable for writing a scalable specification. I think Respec has been widely used in several W3C specs more than Bikeshed, but recently, some major specs have been written by Bikeshed. (e.g. HTML5.3, WebAssembly, and all CSS specs)

* HTML 5.3: https://w3c.github.io/html/
* WebAssembly: https://www.w3.org/TR/wasm-core-1/

Also, there is a `Echidna` tool to make specs officially publish with a url like "https://www.w3.org/TR/".
I think Ted could probably take roles for the publication.
* Spec publication workflow at W3C: https://github.com/w3c/echidna/

If we could select a better editing tool for RSI before our f2f meeting, we would be able to prepare more a bit details before the f2f meeting. I'm wondering the opinion or experience of former editors on VISS/VIAS.

(Could someone put a "RSI" label on this issue?)

**Comment by tguild** [comment]
we are closing outdated issues, please reopen or create a new one if still relevant
