### ISSUE TITLE
VISS, VIWI and VSS moving forward to 2.0

### ISSUE THREAD

**Issue by peterMelco** [w3c/automotive#266]
The question is whether we should use VISS or VIWI or create something from scratch for the next generation api.

To extend VISS according to Ulf Bs suggestion we could start with the following bullets:

- Support a RESTful transport protocol, i. e. HTTP.
- Object model support.
         a.       VSS object model support.
         b.       Query ability on VSS objects.
-  Adding new “services” to VSS, like Media, etc.
- VSS structured as one tree (one common root).

We also have a suggestion from Ulf to do a poll on which way to go.

1) VISS as starting point
2) VIWI as starting point
3) Create something from "scratch"(not in the words full meaning of course)

**Comment by tguild** [comment]
we went with 3, drawing from the others
