### ISSUE TITLE
JSON schema for value seems wrong

### ISSUE THREAD

**Issue by rndwb** [w3c/automotive#275]
The description of the value type says it could be anything, even complex types. But then the JSON schema only allows string. 
What to make of that? Should the 'type' for value be removed?

Here's the relevant part of the spec:
https://github.com/w3c/automotive/blob/gh-pages/vehicle_data/vehicle_information_service.html#L775-L777

**Comment by tguild** [comment]
apologies for the delay, we discussed and agreed. I'll put type="" (undefined/any) in a pull request
