### ISSUE TITLE
Gen2 feature: Authentication and authorization

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#308]
The Gen2 chapter describing this feature will inherit as much as possible from the Volkswagen Infotainment Web Interface (https://www.w3.org/Submission/2019/SUBM-viwi-protocol-20190718/), chapter 7 "User Authentication and Authorization".

**Comment by UlfBj** [comment]
I assign myself to the task of creating this Gen2 chapter from the mentioned VIWI input.

**Comment by tguild** [comment]
Ulf agrees to close, covered in PR
