### ISSUE TITLE
Datatypes

### ISSUE THREAD

**Issue by danielwilms** [w3c/automotive#316]
@UlfBj in #315 [here](https://github.com/w3c/automotive/pull/315#pullrequestreview-313423093)

> The datatypes Float and Double should maybe have references to their exact definitions, as these are not uniquely defined by their names only?

suggestion @wzr1337:
> In order to make it exact how about float32 float64 and float128 to express
float, double and decimal respectively?

**Comment by wzr1337** [comment]
Are we talking about JSON transportation always? Then we do not even need to distinguish between the different float types as they will be sent as characters anyway. 
For a server and client implementation it might be interesting to now the bit size of the float, but we can also just omit overprecise digits or fill underprivileged ones with 0. 

JSON does not even know the difference between integer and number - float. Therefore the RSI spec (https://www.w3.org/Submission/viwi-protocol/) had to introduce this differentiation, as embedded software  clientsand servers - which this protocol was designed for in thefirst place - may need to optimize memory layout according to the expected values. But even in RSI/Viwi the number type is used for any type of floating point precision.

I recommend following the RSI/Viwi spec of course 😜

**Comment by UlfBj** [comment]
>> Are we talking about JSON transportation always?

Yes we are. So you are right, the float/double machine implementation is transparent at payload level. 
We can close the discussion on that. 
Thanks.
