### ISSUE TITLE
[data-spec] DriveMode and DrivingMode

### ISSUE THREAD

**Issue by aShinjiroUrata** [w3c/automotive#33]
<pre>
6.26 DrivingMode Interface
8.6 DriveMode Interface
</pre>
I felt similar name and may be confusing. 
If `DrivingMode` is not commonly used name, how about `DrivingStatus` or some other name?
(I'm not sure about suitable naming.)

**Comment by aShinjiroUrata** [comment]
It looks the name '6.26 DrivingMode' is selected to align with '6.27 NightMode', '6.28 StartStopMode' and so I guess this naming is reasonable from this view point.

On the other hand, '8.6 DriveMode' looks natural name.

Since I don't come up with better alternative for 'DrivingMode', I'd like to keep this as is if other people don't have other opinion.

**Comment by acrofts84** [comment]
I agree that they are very similar. Would 'VehicleInMotion' or 'MotionStatus' be a more appropriate name instead of 'DrivingMode'?

**Comment by aShinjiroUrata** [comment]
Thanks for the input.
My concern is just the names were too similar and so, both `VehicleInMotion`, `MotionStatus` are OK to me. 
For me, I like shorter one. 
If there is no other opinion, I will create pull request with `MotionStatus`.

**Comment by aShinjiroUrata** [comment]
As pull request #46 "renamed DrivingMode to DrivingStatus" already merged, I close this issue.
