### ISSUE TITLE
Gen2 name

### ISSUE THREAD

**Issue by tguild** [w3c/automotive#333]
I want to start moving us toward naming Gen2. Please provide suggestions and if we do not have a clear candidate will setup a survey to decide.

An obvious one is VISS2 although that would in some ways seem wrong if additional data taxonomies besides VSS end up being exposed through it. VISS was solely for VSS whereas Gen2 nominally supports additional data taxonomies.

**Comment by UlfBj** [comment]
Connected Vehicle Specification

**Comment by adobekan** [comment]
Specification of connected vehicle interfaces -> SCENE, SCENT, PIONEER etc.  :)
Connected vehicle interface specification -> CVIS, CENTRIC, VISION, CHIP, CONVERSION etc.

I have tried https://acronymify.com, for generating acronyms in this case.

**Comment by peterMelco** [comment]
I like Connected Vehicle Specification ... the acronym CVS becomes somewhat confusing though :)

**Comment by wonsuk73** [comment]
Connected Vehicle Specification looks quite coool as a name of the spec! But its meaning looks very broad. So I think it might be better if we add an more focused word for the spec to the name. How about Connected Vehicle Interface Specification, CVIS :)

Or If we are willing to develop additional specs related with Connected Vehicle, I might need to think about Series spec. Then Series style name could be better like below.
—> Connected Vehicle - Core Specification
—> Connected Vehicle - Transport Protocol Specification

**Comment by UlfBj** [comment]
With the service catalog initiative in mind, maybe the following could show the relationship between the two.

Connected Vehicle Signal Specification (CVSiS) - the signal interface (current Gen2) 
Connected Vehicle Service Specification (CVSeS) - the service interface

Vehicle Signal Specification (VSiS) - the signal data model and catalog (current VSS)
Vehicle Service Specification (VSeS) - the service data model and catalog

**Comment by tguild** [comment]
Resolved based on survey and discussion

Vehicle Information Service Specification (VISS) version 2

https://lists.w3.org/Archives/Public/public-automotive/2020Oct/0011.html
