### ISSUE TITLE
Issues of status codes

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#335]
Thanks for good progress of Gen2 transport spec. When I read this spec, I would stand for issues below.

Issue 1.  Does it need to have two separated status codes for invalid token as below? If it does, then reason why?
- 401 (Unauthorized) | token_invalid
- 406 (Not Acceptable) | invalid_token

Issue 2. It seems token_invalid might cover a meaning of toke_missing. If toke_missing is required, then could you explain why?
- 401 (Unauthorized) | token_invalid
- 401 (Unauthorized) | token_missing
- 404 (Not Found) | missing_token
- 406 (Not Acceptable) | invalid_token

Thanks!

**Comment by UlfBj** [comment]
Issue 1: 
This is an error, there should not be two status codes for invalid token. The same for missing token (if it should be there at all).

Issue 2:
The invalid token error could be used also for the case of missing token. I guess it is a matter of taste whether there should be a separate error for missing token. I am fine with skipping it if others think so.

**Comment by wonsuk73** [comment]
@UlfBj , Thanks for quick reply.
Regarding issue1, I made two PRs(#337, #338) to remove duplicated errors, invalid token and missing token separately. These separated PRs don't have any meaning. Just I did like that. ^^;;

Regarding issue2, I agreed with you. Let's keep it as of now if anyone doesn't say any strong opinion.

Thanks!

**Comment by wonsuk73** [comment]
@UlfBj @tguild if there is no objection for #337  and #338, could you merge?

**Comment by wonsuk73** [comment]
PRs are merged, so it's done.
