### ISSUE TITLE
Service discovery or signal discovery?

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#339]
The spec chapters describing client request to retrieve metadata from the tree refers to it as "service discovery". 
With the work initiated on writing a service catalog, and the established understanding of the term, maybe it is better to rename it to "signal discovery"? 
Other renaming proposals are welcome.

**Comment by peterMelco** [comment]
Agree that this will be confusing. Signal discovery is fine by me , it seems that signal is a defined term when we describe  vehicle data source .
