### ISSUE TITLE
Historic data

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#344]
* If a node supports storing data, then it should be possible for a client to retrieve it.
* Request for retrieval of historic data points for a just passed period of time
** Query with reserved name $history appended to path
** Period syntax as specified in ISO8601
** Vehicle.Powertrain.BatteryManagement.Battery.AccumulatedChargeEnergy?$historyEQPT4M
* Server responds with all data saved for this period.
** Minimum response is the latest value.
* Primary use case: Vehicle temporarily out of coverage.
** No need for client activation/deactivation

**Comment by peterMelco** [comment]
The use of persistent storage on vehicles is something that we need to keep optional. Oems needs to be able to estimate life expectancy of a vehicle and have that matched to the number of available writes to storage media.

**Comment by tguild** [comment]
I am in favor of historic data but wonder if there should be a mechanism to instruct the service of data that would be desirable, stored subscriptions and data collection occurs regardless of the application running

**Comment by tguild** [comment]
Ted's idea compliments and doesn't block Ulf's

**Comment by UlfBj** [comment]
Solved in PR#362.
