### ISSUE TITLE
POST as a new transport protocol method

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#347]
In the current VISS ver 2 specification URL query syntax is used to augment the GET functionality. This syntax has the disadvantage of possibly creating rather unreadable URLs. An example of this was shown in my proposal to add client functionality to enable a client to express multiple signal paths to random nodes in the tree in one request, which led Adnan to propose to use POST, and place the query data in the message payload. 
I think this is an excellent idea, which should be used to transform all current queries in the spec into POST plus payload expressions. The example I showed for multiple paths,
```
GET  Vehicle.Powertrain.BatteryManagement.Battery.AccumulatedChargeEnergy?$pathsEQ[Vehicle.Cabin.Infotainment.Navigation.CurrentLocation.Latitude, Vehicle.Cabin.Infotainment.Navigation.CurrentLocation.Longitude]
```
Would then be transformed into something like
```
POST Vehicle.Powertrain.BatteryManagement.Battery.AccumulatedChargeEnergy   {“filter”:{“paths”:["Vehicle.Cabin.Infotainment.Navigation.CurrentLocation.Latitude", "Vehicle.Cabin.Infotainment.Navigation.CurrentLocation.Longitude"]}}
```
The POST method would be applied to both the HTTP and Websocket protocols.

**Comment by tguild** [comment]
Not doing POST, see 348

https://www.w3.org/2020/11/10-auto-minutes.html
