### ISSUE TITLE
Mission statement ungrammatical

### ISSUE THREAD

**Issue by samuelweiler** [w3c/automotive#352]
"The mission of the Automotive Working Group is to develop Open Web Platform specifications for in-vehicle and cloud based uses through vehicle data access and service protocols."

leaves me wondering "uses of what"?  And, by itself, the sentence doesn't make much sense to me.

Would you clean this sentence up?

**Comment by tguild** [comment]
Specifications are for use within the vehicle and cloud. This is a bit of an awkward sentence, added a comma and minor rephrasing.

**Comment by samuelweiler** [comment]
The phrasing still leaves me wondering "uses of what"?
