### ISSUE TITLE
Remove redundant priv and sec comments

### ISSUE THREAD

**Issue by samuelweiler** [w3c/automotive#353]
Please remove this line from section 1: "The specification(s) produced by this Working Group will include security and privacy considerations."  as well as one of these two duplicate lines in section 3: "Each specification should contain a section detailing any known security or privacy implications for implementers, Web authors, and end users."

**Comment by tguild** [comment]
Thanks, done. The duplicate statement was a carryover from old charter into new template cf Chris Lilley's complaint last week on Strat call.
