### ISSUE TITLE
Fragments are not transported over HTTP

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#365]
The chapter "Metadata Request" in the CORE spec says that the syntax uses a fragment component as shown below
HTTP GET
URL: Vehicle/ADAS/ABS#static-metadata (or dynamic-metadata). 
The problem with this is that HTTP removes the fragment before issuing the request. 
Information about it can be found here
https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/
I would therefore like to propose that the request instead uses the query syntax as shown below.
HTTP GET
URL: Vehicle/ADAS/ABS?metadata=static (or dynamic).

**Comment by peterMelco** [comment]
Look good to me...actually I like this more than the previous suggestion.

**Comment by tguild** [comment]
Using querystring instead
