### ISSUE TITLE
Feature: Endpoint to request outside temprature measured by the car

### ISSUE THREAD

**Issue by dkdndes** [w3c/automotive#379]
The endpoint enables the request of the currently measured outside temperature.

**Comment by petervolvowinz** [comment]
I am not sure what you mean ? Do you want to add a signal to the VSS signal tree ? That should perhaps be better adressed by : https://github.com/GENIVI/vehicle_signal_specification

**Comment by erikbosch** [comment]
There is a signal AmbientAirTemperature in https://github.com/GENIVI/vehicle_signal_specification/blob/3e39406be384be636b1040fd5248a10d44a0e06d/spec/Vehicle/Vehicle.vspec

**Comment by petervolvowinz** [comment]
Then we could close this one.

**Comment by dkdndes** [comment]
I assumed this W3C repository objective is to generate a generic description of automotive endpoints & standard, not producer-related solutions.  Due to this, I am not sure if your answer is correct? It does show a solution of three particular car producers, or I am mistaken? 

That's why I ask if it would be possible to include an endpoint of this type in this automotive standard? Background for my questions is the following use-case: 

If we assume, we can collect from any driving vehicle outside temperature data, and we can generate a pretty good summary of the weather situation (except within a parking garage or a tunnel or similar).

If then the permission exists to collect the data (jointly with the geo-coordinates of the measurements) - from an open data vehicle company server - it could help to improve weather forecasting and improve accuracy.

The temperature data collected at the height of a car is different from the temperature data collected via the Arial observation point (Satelite, plane, balloon, weather-station at buildings, etc.). The number of cars if fare bigger than the number of existing weather stations.

I hope this is interesting, and you might consider including the idea in your plans for this repository. I saw your repository readme, and it stated:

* /vehicle_data/ - working copies of the vehicle and information API specifications

and that for development data will be available for easy consumption. The signal specification you mentioned above is in practice more for (internal) automotive analysis, and not for additional, external (non-automotive) services intended.

**Comment by peterMelco** [comment]
The use case a such is interesting but its not what viss v2 is aiming to
standardize.  Please see the spec charter. Its an api and protocol to
access vehicle signals using vss as data model. The realization of your
endpoint is beoynd our current scope.

**Comment by gunnarx** [comment]
Hi @dkdndes 

> I assumed this W3C repository objective is to generate a generic description of automotive endpoints & standard, not producer-related solutions. 

I will try to answer it using other words.  The [VSS](https://github.com/GENIVI/vehicle_signal_specification) is the data description format (and content) that is used by the W3C specification of the VISS communication protocol.    In other words, VSS-defined data is carried by the VISS protocol. 

In addition to describing the _rules_ for how to describe _any_ data which the VISS protocol can then give access to, VSS also aims to define a standard collection of data definitions.

Any and all vehicle manufacturers are welcome to use and contribute to VSS which is an open-source licensed project, and any stakeholders that wish to affect it can. The copyright statements you can see the README seem to be misleading and probably also incomplete.  (But I don't think that changes anything fundamental in this discussion anyway)

In the end, the specific VISS project deals with only the data protocol definition as @peterMelco described.  On the larger scale however, I think you have the right idea about the overall intentions of W3C here:  To establish a kind of common automotive interface.  The thing to understand is that that idea is  being _realized_ by leveraging the signal definitions (rules and content) described in the VSS project.  (And the same idea is admittedly also being realized through **other** related projects around VSS).

In fact, there is an even bigger picture we have for aligning the full industry behind a common data standard and for that I would suggest to introduce you to the **CVII** which is already a significant industry alignment discussion, but it was started by W3C and GENIVI together.  Here is [a page with a lot of information](https://at.projects.genivi.org/wiki/display/DIRO/Common+Vehicle+Interface+Initiative+--+Home).

On the specific request, the data item you requested seems to already exist, as @erikbosch noted.

**Comment by tguild** [comment]
@dkdndes I'll also add that this common data model VSS used inside the vehicle is also being encouraged for use in the cloud by auto manufacturers and telematics providers. We have a Graph schema and ontology so the end points are possible modulo privacy complications. 

I for one would consent to providing a number of unattributed data points including ambient temperature for a wide range of purposes. Some private data stores are doing what you describe, mapping out more precise weather. I am part of a grant proposal to try to expose various vehicle data to researchers while addressing privacy/usage concerns.

**Comment by tguild** [comment]
@dkdndes closing issue as the data point is there and @erikbosch provided link to repo where individual signals are defined, do please feel free to prose additional there and even contribute definitions in YAML
