### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by djensen47** [w3c/automotive#4]
The README needs to be fleshed out:
- [x] Brief introduction about the group and the spec
- [x] Repo layout: where do files live. This was discussed in a recent meeting but should be documented in the README
- [x] Style and/or code guidelines. Links are good enough.
- [x] Contribution guidelines: any instructions on how to contribute and who is allowed to contribute (e.g., members), and CLA requirements, etc.
   - It might be a good idea to have a separate CONTRIBUTORS.md file with a list of folks who have and can contribute. It might make lief easier on the editors.
- [x] Tools used. E.g., a link to Respec

**Comment by djensen47** [comment]
- [ ] @djensen47 to provide a pull request

**Comment by acrofts84** [comment]
I've submitted and merged a pull request on this with an update in each section. As we expand I'll make sure to keep it up to date. In terms of contributions, I've linked to the Charter which covers licencing, and those who have contributed can be found <a  href="https://github.com/w3c/automotive/graphs/contributors">here</a> within GitHub.
