### ISSUE TITLE
Suggestion for stronger limitation for multipath set/update request to server 

### ISSUE THREAD

**Issue by crea7or** [w3c/automotive#403]
As the documentation says:
`The client may request that the server sets the value of one or more signals e.g. to lock one or more doors or open a window by sending a setRequest message to the server. In the case of several signals being set, they MUST all be of the same data type, and be set to the same value. `

It looks like it can be limited to "the instances of the same node" and then there should be the option to know that two(or more) signals is the instances of the one template from vss.

**Comment by crea7or** [comment]
As an opposite move to this change, set/update request could be made free to change different values with different types. It looks like it is required for proper changing of aggregated values (to receive valid subscription events for an agregate values).

**Comment by wonsuk73** [comment]
@crea7or, Do you have a proposal for this? It looks like it's not easy to solve with convenient use. In addition I think it's related with issue #417. Am I right?

**Comment by crea7or** [comment]
@wonsuk73 the first message is about stronger clarifying of documentation. Because it's not really clear what to do with multiset signals when one value can not be set due to validation error etc. With this clarification errors in multi-set will be the same for all values or everything will pass. The second message actually shouldn't be there so please, ignore it because of #417.
