### ISSUE TITLE
The data inconsistency in filters for paths and metadata requests

### ISSUE THREAD

**Issue by crea7or** [w3c/automotive#405]
For paths filter the specifications says we should use array of strings (paths pieces). 

```
"filter": {"op-type":"paths", "op-value":["Door/*/*/IsOpen", "DriverPosition"]}
```

For metadata filter the specification says we should use string with properties delimited by '+' sign.
```
"filter":"{"op-type":"metadata", "op-value":"dynamic", "op-extra":"availability+validate"}
```

Why not to use array in case of metadata for a consistency across API?

**Comment by UlfBj** [comment]
Fixed in PR#408
