### ISSUE TITLE
Proposal to add current value to the response on subscribe request

### ISSUE THREAD

**Issue by crea7or** [w3c/automotive#410]
It's useful because allow us to avoid additional requests since sometimes you need to know current value before subscription will be triggered.

```
{
  "action": "subscribe",
  "data": {
    "dp": {
      "ts": "2020-04-15T13:37:00Z",
      "value": "2000"
    },
    "path": "Vehicle/Drivetrain/InternalCombustionEngine/RPM"
  },
  "requestId": "6578",
  "subscriptionId": "12345",
  "ts": "2020-04-15T13:37:00Z"
}
```

**Comment by wonsuk73** [comment]
@crea7or, Thanks for the proposal. Can I ask specific use cases for this?

**Comment by crea7or** [comment]
@wonsuk73 a health signal for example. App want to know a health of some component and subsribes to the health signal. But what is current health of this component is unknown until app will request signal explicitly as separate request or wait untill subscribtion will be trigered.

**Comment by wonsuk73** [comment]
@crea7or, I am not sure for this kind of use case we need to add this feature because we need to focus major features.

**Comment by crea7or** [comment]
@wonsuk73 this is only a small optimization so absolutely low priority.

**Comment by wonsuk73** [comment]
@crea7or, Thanks.
