### ISSUE TITLE
Set request syntax for arrays

### ISSUE THREAD

**Issue by crea7or** [w3c/automotive#420]
Vehicle Signal Specification [supports arrays](http://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/), but there is no documentation on how to set them, even receive format is not mentioned in the transport documentation. I suppose `set` should be documented like this? 

```
{
  "action": "set",
  "path": "Vehicle/Diagnostic/DTC",
  "value": ["823837", "928273", "736356"],
  "requestId": "5687"
}
```

and `get` will use datapoint mechanism in favor of the regular value get:

 ```
{
  "action": "get",
  "data": {
    "dp": {
      "ts": "2020-04-15T13:37:00Z",
      "value": [
        "823837",
        "928273",
        "736356"
      ]
    },
    "path": "Vehicle/Diagnostic/DTC"
  },
  "requestId": "5687"
}
```

**Comment by UlfBj** [comment]
Fixed in PR421
