### ISSUE TITLE
CORE and TRANSPORT cross reference

### ISSUE THREAD

**Issue by UlfBj** [w3c/automotive#441]
Wonsuk brought this up here
https://github.com/w3c/automotive/pull/440#discussion_r782645960
How is it best solved?

**Comment by UlfBj** [comment]
Solved by using [[viss2-core]] and [[viss2-transport]] syntax. 
Generates entry in References chapter that points to the public FPWD versions. 
Pushed to PR #442

**Comment by wonsuk73** [comment]
@UlfBj Great job! 👍 
I am going to do cross-check two docs for looking for missing pieces on cross reference btw docs :)

**Comment by wonsuk73** [comment]
Regarding cross-reference issue, when I checked other specs as web payments, I see they also use URL of Latest published version in the specs to solve the link breaking problem on official publication process. So I have made a PR #444 to have a feedback. @UlfBj, Is it okay to you? 

If we have a consensus on this way, I am going to make PRs to apply for whole two specs.
