### ISSUE TITLE
Publication cycle of the specs in WD level

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#447]
Recently I made three contributions to apply cross references between VISSv2 Core and VISSv2 Transport. It's helpful to readers of the specs when they check the parts of the specs related with contents they see. But to overcome link breaking issue between recent editor's drafts(Core and Transport) URLs of officially published docs are used because it uses a fixed url regardless of published version the specs (e.g. https://www.w3.org/TR/viss2-core/). 

When I tried to make links between docs there is the issues because of the big gap between published spec and editor's draft. As you know we had published FPWD of Core and Transport specs around 8 months ago, so there are many changes in the specs.

So I would like to propose to make a  publication cycle of the specs in working draft level as every quarter or every half of the year.

**Comment by UlfBj** [comment]
Carine will set it up so that the published version will be the same as the branch.

**Comment by wonsuk73** [comment]
@UlfBj Great! Thanks!  I think there are some more works we need to do after published WD.
