### ISSUE TITLE
Refer to RFC 3987 or URL

### ISSUE THREAD

**Issue by xfq** [w3c/automotive#457]
https://www.w3.org/TR/viss2-core/#address

> Addressing of resources is done using URIs as defined in [[RFC3986](https://www.w3.org/TR/viss2-core/#bib-rfc3986)].

The specification refers to RFC 3986 for addressing of resources. This reference should be changed to [RFC 3987](https://www.rfc-editor.org/rfc/rfc3987) or the WHATWG [URL Standard](https://url.spec.whatwg.org/), to allow for using IDNs and non-ASCII paths.

**Comment by UlfBj** [comment]
Fixed in [RFC3986 reference changed to RFC3987](https://github.com/w3c/automotive/pull/458#top)
#458

**Comment by xfq** [comment]
Thank you. The i18n WG is *satisfied* with the change.
