### ISSUE TITLE
Potential support of structs in VSS

### ISSUE THREAD

**Issue by erikbosch** [w3c/automotive#461]
For information, there are discussions in VSS to support structs. It could be an idea to discuss implications/expectations on VISS, so that we agree on how it might affect the standard and reference implementation. Potential topics:

- Is it clear in current VSS spec how a structure will be represented as payload?
- Other implications, willo it e.g. be possible to use filters on struct data?

References:

- [Issue with long discussion](https://github.com/COVESA/vehicle_signal_specification/issues/326)
- [PR with draft syntax proposal and expectations on implementations](https://github.com/COVESA/vehicle_signal_specification/pull/511)

**Comment by UlfBj** [comment]
It is to my knowledge not clear, or discussed, how a struct should be represented in a payload. 
I am not in favor of the paradigm to define structs using nodes in the tree. This will e. g. significantly increase the complexity of a tree parser. 
Applying the filter model to struct data would add another dimension of complexity, as I see it. 
My current view is that if this is to be supported, it will have to be in a coming version of VISS, not v2.

**Comment by tguild** [comment]
discussed on 2023-04-04 call, as struct is moving forward in VSS we should address here as well. Ulf to draft a solution to accommodate

**Comment by UlfBj** [comment]
Fixed in PR480
