### ISSUE TITLE
documentation: subscription timestamp

### ISSUE THREAD

**Issue by aw-muc** [w3c/automotive#462]
Within the https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Transport.html#subscribe documentation, the subscriptionNotification is described as followed

Object Name | Attribute | Type | Required
-- | -- | -- | --
action | Action | Yes
subscriptionId | string | Yes
data | object/array | Yes

Within the examples, the following is documented:
Notification:

              {
                "action": "subscription",
                "subscriptionId": "12345",
                “data”: {“path”: ”Vehicle.Drivetrain.FuelSystem.Level”, 
                        “dp”: {“value”: ”50”, “ts”: ”2020-04-15T13:37:00Z”}
                },
                **"ts": "2020-04-15T13:37:00Z"**
              }
               
As you can see the example has an additional timestamp mentioned, which is not part of the documentation of the subscribeNotification;

Can you please clarify, what is the correct implementation?

**Comment by UlfBj** [comment]
Subscription notification messages shall have a timestamp. 
That is added to the table in PR#471.

**Comment by aw-muc** [comment]
Awesome; @UlfBj will the issue automatically be closed, when pull request is merged?

**Comment by UlfBj** [comment]
@aw-muc It will be closed at the WG meeting when it is merged. Thanks for finding this documentation error.

**Comment by UlfBj** [comment]
Fixed in PR#471
