### ISSUE TITLE
Subscription handling on error or JWT auth issues (timed out)

### ISSUE THREAD

**Issue by aw-muc** [w3c/automotive#463]
I did not find any clear instruction about the handling of subscriptions if they run into an error like authentication error. 

For example, i have a time based subscription, where the servers sends every 5 seconds notification about the current value I have subscribed with an valid JWT for time X; after time X the internal check runs into an issue, because the JWT is not longer valid; From the documentation the client now gets every 5 seconds an error notification that the JWT is outdated because of auth errors.

Is this a valid behavior, or are there any valid reasons for the severs to close a subscription if he recognizes an error that can't be fixed by the server e.g. JWT is outdated.

**Comment by UlfBj** [comment]
It is in my view probably a reasonable behavior that a server closes a subscription when it recognizes an error that it cannot fix, and sends an error message to the subscriber.

**Comment by aw-muc** [comment]
Would it make sense that these type of behavior are documented somewhere; Because at the moment I havn't found any kind of documentation pointing into that direction;

**Comment by UlfBj** [comment]
@aw-muc It will be documented in the specification, but a discussion and a decision must first take place in the WG. 
Thanks for bringing this issue up.

**Comment by UlfBj** [comment]
Fixed in PR478
