### ISSUE TITLE
VISS Core&transport - unclear MAY with enumeration

### ISSUE THREAD

**Issue by Ilmarinen100** [w3c/automotive#473]
The VISSv2 Core and transport spec contain multiple definitions like this:
> subscriptionId - string - Value returned by the server to uniquely identify each subscription. The value MAY be an integer or a Universally Unique Identifier (UUID).

This appears to say that the id can alternatively be chosen arbitrarily as long as it is encoded into a string
Is that the intended meaning or was a more strict interpretation planned, e.g. the value MUST be either of the following:
* an integer (range?) encoded as a decimal string
* a uuid encoded as lowercase hexadecimal string (with standard 8-4-4-4-12 notation)

**Comment by UlfBj** [comment]
>>This appears to say that the id can alternatively be chosen arbitrarily as long as it is encoded into a string

Yes, that is the correct interpretation of the somewhat unclear statement in the spec. This statement will be updated to become clearer.

**Comment by UlfBj** [comment]
Fixed in PR475
