### ISSUE TITLE
[data_spec] Use-Cases is not consistent with the interface function defined

### ISSUE THREAD

**Issue by QingAn** [w3c/automotive#7]
In http://www.w3.org/2014/automotive/data_spec.html#use-cases the summary of use-cases is not consistent with the interfaces defined.

For example, Use Cases for Vision interfaces, http://www.w3.org/2014/automotive/data_spec.html#use-cases-for-vision-interfaces It says that:
- To warn when the vehicle goes on another lane (Lane departure warning function)
- To warn in case of an danger (vehicle, pedestrian, animals, stop sign, red light, ...)
- To record the scene before and after an accident (for insurance or testimony)
- To improve vision in the dark

However, in http://www.w3.org/2014/automotive/data_spec.html#vision-parking-interfaces 
- the LaneDepartureDetection Interface http://www.w3.org/2014/automotive/data_spec.html#lanedeparturedetection-interface can just return current status of Lane departure warning function; 
- the Alarm Interface  http://www.w3.org/2014/automotive/data_spec.html#alarm-interface can just return current status of In vehicle Alarm System

**Comment by djensen47** [comment]
Action items:

- [ ] Look at other specs such as Web Payments
- [ ] Include rationale explaining how we're doing use cases and why
  - In the spec or companion document?
