### ISSUE TITLE
Missing support for the following key electric vehicle functionality (from Robert of Evergreen Consulting)

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#79]
After Robert from Evergreen Consulting reviewed the specs from the WG, he proposed below items are required to be added. It makes sense to me. @acrofts84 @aShinjiroUrata @QingAn @djensen47 @paulboyes @tobie  What do you think?

1) Charger info (rather than battery info)
- charger_pilot_current
- charger_actual_current
- charger_power  
- fast_charger_present

2) Charging control
- Set Charge Limit
- Get Charge Limit
- Start Charging
- Stop Charging

3) Fuel temperature by zone (to cover battery temperature)

**Comment by tguild** [comment]
Earlier WebIDL spec. VISS defers to external data model and it has electric signals
https://github.com/GENIVI/vehicle_signal_specification/
