### ISSUE TITLE
Action Items to Refactor the Automotive API

### ISSUE THREAD

**Issue by djensen47** [w3c/automotive#80]
As discussed in the meeting on Feb. 16
- [x]  Discussion on how the service (websocket/rest-ish) approach works with strawman examples.
- [ ] Determine the architecture and diagram it. (Look at Web of Things).
- [ ] Convert WebIDL in the data spec to JSON or JSON-LD.
- [ ] Validate that a higher level API can be implemented using the newly proposed low-level API.
- [x] Close #37
- [ ] Close #72

**Comment by djensen47** [comment]
Started the discussion on #81 
Closed #37

**Comment by wonsuk73** [comment]
@djensen47 I think Signal Naming Convention is also one of important item we need to make for websocket/rest-ish approach. What do you think?
